# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  native:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        arch:
          - amd64
#          - arm64
    name: Linux binary ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Update System
      run: sudo apt-get update -y
    - name: Install qemu
      run: sudo apt-get install -y --no-install-recommends qemu-user-static
    - name: Experimental Docker
      run: sudo cp .github/experimental-docker.json /etc/docker/daemon.json
    - name: Restart Docker
      run: sudo systemctl restart docker.service
    - name: pull docker image
      run: docker pull --platform $(echo ${{ matrix.arch }} | sed 's|-|/|g') ubuntu:20.04 || true
    - name: build in docker
      run: docker run --rm --ulimit memlock=10000000:10000000 -v $GITHUB_WORKSPACE:/work ubuntu:20.04 /work/.github/workflows/build.sh
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: shared-lib-${{ matrix.arch }}
        path: build/libs/main/*.so