# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - x86_64
          - arm64
    name: Build on ${{ matrix.arch }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Update System
      run: sudo apt-get update -q -y
    - name: Experimental Docker
      run: sudo cp .github/experimental-docker.json /etc/docker/daemon.json
    - name: Restart Docker
      run: sudo systemctl restart docker.service
    - name: pull docker image
      run: docker pull dockcross/linux-$(echo ${{ matrix.arch }} | sed 's|-|/|g')-full || true
    - name: build in docker
      run: docker run --rm --ulimit memlock=-1:-1 -v $GITHUB_WORKSPACE:/work ubuntu:20.04 /work/.github/workflows/build.sh
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: jasyncfio-${{ matrix.arch }}
        path: build/libs/*.jar
