# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build on amd64
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu20.04
        githubToken: ${{ github.token }}
        shell: /bin/sh
        install: |
          apt-get update -y
          apt-get install -y --no-install-recommends openjdk-8-jdk make gcc g++ libc6-dev
        run: |
          which java
#          ./gradlew build --no-daemon
    - name: Show
      run: |
        ls -al "${PWD}"

#    - name: Update System
#      run: sudo apt-get update -y
#    - name: Install qemu
#      run: sudo apt-get install -y --no-install-recommends qemu-user-static
#    - name: Experimental Docker
#      run: sudo cp .github/experimental-docker.json /etc/docker/daemon.json
#    - name: Restart Docker
#      run: sudo systemctl restart docker.service
#    - name: pull docker image
#      run: docker pull --platform $(echo ${{ matrix.arch }} | sed 's|-|/|g') ubuntu:20.04 || true
#    - name: build in docker
#      run: docker run --rm --ulimit memlock=-1:-1 -v $GITHUB_WORKSPACE:/work ubuntu:20.04 /work/.github/workflows/build.sh
#    - name: Upload
#      uses: actions/upload-artifact@v2
#      with:
#        name: jasyncfio-${{ matrix.arch }}
#        path: build/libs/*.jar
