name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - amd64
#          - arm64
    name: Release on ${{ matrix.arch }}
    steps:

      - name: Git checkout
        uses: actions/checkout@v2
      - name: Update System
        run: sudo apt-get update -q -y
      - name: Install qemu
        run: sudo apt-get -qq install -y qemu qemu-user-static
      - name: Docker deps
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Experimental Docker
        run: sudo cp .github/experimental-docker.json /etc/docker/daemon.json
      - name: Restart Docker
        run: sudo systemctl restart docker.service
      - name: pull docker image
        run: docker pull --platform $(echo ${{ matrix.arch }} | sed 's|-|/|g') ubuntu:20.04 || true
      - name: Install gpg secret key
        run: |
          echo -n "${{ secrets.GPG_PRIVATE_KEY }}" > $GITHUB_WORKSPACE/release.gpg
      - name: build in docker
        run: | 
          docker run -e S_USERNAME -e S_PASSWORD -e VERSION -e PASSPHRASE  --rm --ulimit memlock=-1:-1 -v $GITHUB_WORKSPACE:/work ubuntu:20.04 /work/.github/workflows/build.sh release
        env:
          S_USERNAME: ${{ secrets.S_USERNAME }}
          S_PASSWORD: ${{ secrets.S_PASSWORD }}
          VERSION: ${{ github.event.inputs.version }}
          PASSPHRASE: ${{ secrets.GPG_SECRET }}