name: Releases

on:
  push:
    tags:
      - 'releasebuild-*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/main/*.jar"
#          bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}
